version: "3.8"

services:
  chrome:
    image: selenium/node-chrome:4.12.1
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 8
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2000000000
    networks:
      - app
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  selenium-hub:
    image: selenium/hub:4.12.1
    ports:
      - 4444:4444
    networks:
      - app

networks:
  app:
    external: true
