version: "3.8"

services:
  nginx:
    image: nginx:1.20.0-alpine
    labels:
      - app=nginx
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: any
        delay: 1s
        window: 10s
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 3000
        target: 3000
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    networks:
      - app

  cars-backend-hidden:
    labels:
      - app=backend
    image: blakexxxd/cars-backend:latest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - app
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: any
        delay: 1s
        window: 10s
    env_file: backend-hidden.env

  cars-backend:
    labels:
      - app=backend
    image: blakexxxd/cars-backend:latest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - app
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: any
        delay: 1s
        window: 10s
    env_file: backend.env

networks:
  app:
    external: true
